IMAGE_SIZE = 128

# object parameters
MIN_NUM_OBJS = 1
MAX_NUM_OBJS = 2
NUM_QUERIES = 32
ROT_DEG_AUG = 15
MIN_OBJS_SIZE = 10
MAX_OBJS_SIZE = 40

# model parameters
D_MODEL = 512
BACKBONE_NUM_LAYERS = 18
FEATURE_HEIGHT = IMAGE_SIZE // 8
FEATURE_WIDTH = IMAGE_SIZE // 8
NUM_CLASSES = 3  # background, rectangle, circle
DROPOUT = 0.15

# training parameters
BATCH_SIZE = 32
NUM_EPOCHS = 20
LEARNING_RATE = 1e-5
WEIGHT_DECAY = 1e-5
NUM_WORKERS = 4
CLASS_LOSS_WEIGHT = 5.0
BBOX_LOSS_WEIGHT = 1.0
MATCHER_CLASS_WEIGHT = 5.0
MATCHER_BBOX_WEIGHT = 1.0
CHECKPOINT_DIR = "checkpoints"
CHECKPOINT_EVERY_N_EPOCHS = 1
